export const suggestions = [
  { value: "Popular Search", label: "Popular Services", isDisabled: true },
  { value: "Diagnostic Evaluation", label: "Diagnostic Evaluation" },
  { value: "Occupational Therapy", label: "Occupational Therapy" },
  { value: "Speech Therapy", label: "Speech Therapy" },
  { value: "School-Based Service", label: "School-Based Service" },
  { value: "Music Therapy", label: "Music Therapy" },
  { value: "Art As Therapy", label: "Art As Therapy" },
  { value: "ABA Therapy", label: "ABA Therapy" },
  { value: "A-Z Services", label: "Popular Services", isDisabled: true },
  { value: "Dance Movement", label: "Dance Movement" },
  { value: "Art as Therapy", label: "Art as Therapy" },
  { value: "Counselling", label: "Counselling" },
  { value: "Social Skills Group", label: "Social Skills Group" },
];
